# Generated by Django 3.2.16 on 2023-07-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_auto_20230701_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultid',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
